<?php
class Hilo {
    public $alumnos;
    public $conferencia;
    public function __construct($alumnos,$conferencia){
        $this->conferencia=$conferencia;
        $this->alumnos=$alumnos;
    }

    public function run()
    {
        // TODO: Change the autogenerated stub
        require_once "../helpers/conexion.php";
        $db=new ConexionBD();
        $conexion=$db->getConnection();
        $correo=array();
        while($alumno=mysqli_fetch_assoc($this->alumnos)){
            $nc=$alumno['nc'];
            $datos=mysqli_query($conexion,"SELECT correo FROM Alumno WHERE nc='$nc'");
            $datosalu=mysqli_fetch_assoc($datos);
            array_push($correo,$datosalu['correo']);
        }
        require_once "../correo/correo.php";
        $mail=new Correo();
        $mail->enviar_correo_conferencia($correo,$this->conferencia);
    }
}
?>